### ISSUE TITLE
大佬排版算法怎么搞呢

### ISSUE THREAD

**Issue by wbb18129355955** [Trisia/ofdrw#1]

**Comment by Trisia** [comment]
排版目前还在策划中呢，


拟定采用 类似于 HTML 的盒式模型

不过下一步还是先准备下虚拟容器和打包的，布局和排版要推后了吧

**Comment by Trisia** [comment]
> _No description provided._

排版算法请参考 [《OFD R&W 布局设计》](https://github.com/Trisia/ofdrw/blob/master/ofdrw-layout/doc/README.md)
