### ISSUE TITLE
存在乱码及换行问题

### ISSUE THREAD

**Issue by ChinaTjcm** [Trisia/ofdrw#10]
感谢作者辛苦工作！

目前使用 永中Office 打开 会乱码

使用新版 新科阅读器 HelloWorld.ofd 会 W riter 显示，在尝试阅读代码绘制发票标样！先 mark 为敬。

**Comment by Trisia** [comment]
目前我知道的是OFD RW 产生的文档中使用 OpenType的字体格式并且内嵌到了OFD文档中，但是数科阅读器，不会主动加载内嵌在OFD中的字体，而是从操作系统中取字体，不知道是我实现存在问题还是他们的BUG。

关于你说的  永中Office 我没有试验过，不过你可以给我个下载安装链接吗？我也尝试一下。

感谢老铁的支持哦

**Comment by ChinaTjcm** [comment]
永中 Office 下载链接：
http://www.yozodcs.com/page/personalOffice.html

我理解了你的想法，我今天尝试用代码画发票表样，如果有成果，我当 Junit 提交合并申请~

老铁一起加油！

**Comment by Trisia** [comment]
加油！奥利给

如果该问题得到了解决，请关闭问题哦。

**Comment by Trisia** [comment]
> 永中 Office 下载链接：
> http://www.yozodcs.com/page/personalOffice.html
> 
> 我理解了你的想法，我今天尝试用代码画发票表样，如果有成果，我当 Junit 提交合并申请~
> 
> 老铁一起加油！

老铁你在使用过程中如果有觉得不好用的地方，或需要支持到的功能，可以提交Issue哦。

**Comment by Trisia** [comment]
新的版本中实现了 行内 通过`\n`进行换行的功能
![image](https://user-images.githubusercontent.com/17817790/79980773-337e3b80-84d6-11ea-8459-74602faa2f74.png)

效果如下：

![image](https://user-images.githubusercontent.com/17817790/79980800-3c6f0d00-84d6-11ea-80b0-a83b2cede0c0.png)


该功能预计会在 **1.2.0** 中发布
