### ISSUE TITLE
警告：Modifying the current transformation matrix is not allowed within text objects

### ISSUE THREAD

**Issue by xiangyanggong** [Trisia/ofdrw#105]
转换OFD文件成功，但在转换过程中打印了一些警告信息，不知道是什么原因？
Jan 25, 2021 2:04:46 PM org.apache.pdfbox.pdmodel.PDPageContentStream transform
WARNING: Modifying the current transformation matrix is not allowed within text objects.
Jan 25, 2021 2:04:46 PM org.apache.pdfbox.pdmodel.PDPageContentStream transform
WARNING: Modifying the current transformation matrix is not allowed within text objects.
Jan 25, 2021 2:04:46 PM org.apache.pdfbox.jbig2.util.log.JDKLogger info
INFO: page 1 speed time 5
Use: 481 ms
生成文档位置: E:\idea_workspace\maven\user1\src\main\resources\result\15.pdf

**Comment by Trisia** [comment]
转换问题，由于相关模块的开发者最近比较繁忙，可能响应比较慢。

**Comment by DLTech21** [comment]
warning是pdfbox的日志，可以忽略
