### ISSUE TITLE
在Linux环境下由于路径大小写敏感导致读取OFD文件失败

### ISSUE THREAD

**Issue by agzou** [Trisia/ofdrw#106]
在**Linux**环境下，由于路径大小写敏感问题，导致读不到\Doc_0\Tpls\Tpl_0下内容。
[测试ofd文件](https://github.com/Trisia/ofdrw/blob/master/ofdrw-converter/src/test/resources/%E5%8F%91%E7%A5%A8%E7%A4%BA%E4%BE%8B.ofd)
重现如下（系统Ubuntu20.04）:
``` java
    @PostMapping("/odfToPdf")
    public void ofdToPdf(MultipartFile file, HttpServletResponse response) throws IOException {
        try (InputStream input = file.getInputStream(); OutputStream output = response.getOutputStream()) {
            response.setContentType(MediaType.APPLICATION_PDF_VALUE);
            ConvertHelper.toPdf(input, output);
        }
    }
```
> 报错
org.ofdrw.reader.ErrorPathException: 无法切换路径到TPLS/Tpl_0/，目录不存在。
	at org.ofdrw.reader.ResourceLocator.cd(ResourceLocator.java:233) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:376) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:352) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.reader.DLOFDReader.getTemplateInfo(DLOFDReader.java:135) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.reader.DLOFDReader.getOFDPageVO(DLOFDReader.java:157) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.reader.DLOFDReader.initReader(DLOFDReader.java:88) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.reader.DLOFDReader.<init>(DLOFDReader.java:63) ~[ofdrw-reader-1.7.3.jar:na]
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:41) ~[ofdrw-converter-1.7.3.jar:na]
	at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:107) ~[ofdrw-converter-1.7.3.jar:na]

**经过debug,发现解压的ofd文件目录为\Doc_0\Tpls\Tpl_0，但是读取到Document.xml->TemplatePage->BaseLoc 为TPLS/Tpl_0/Content.xml，
Windows系统下文件路径大小写不敏感不会报错，但是Linux下会报错。**

**Comment by Trisia** [comment]
装换问题，由于相关模块的开发者最近比较繁忙，可能响应比较慢。

**Comment by Trisia** [comment]
> 在**Linux**环境下，由于路径大小写敏感问题，导致读不到\Doc_0\Tpls\Tpl_0下内容。
> [测试ofd文件](https://github.com/Trisia/ofdrw/blob/master/ofdrw-converter/src/test/resources/%E5%8F%91%E7%A5%A8%E7%A4%BA%E4%BE%8B.ofd)
> 重现如下（系统Ubuntu20.04）:
> 
> ```java
>     @PostMapping("/odfToPdf")
>     public void ofdToPdf(MultipartFile file, HttpServletResponse response) throws IOException {
>         try (InputStream input = file.getInputStream(); OutputStream output = response.getOutputStream()) {
>             response.setContentType(MediaType.APPLICATION_PDF_VALUE);
>             ConvertHelper.toPdf(input, output);
>         }
>     }
> ```
> 
> > 报错
> > org.ofdrw.reader.ErrorPathException: 无法切换路径到TPLS/Tpl_0/，目录不存在。
> > at org.ofdrw.reader.ResourceLocator.cd(ResourceLocator.java:233) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:376) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:352) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.getTemplateInfo(DLOFDReader.java:135) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.getOFDPageVO(DLOFDReader.java:157) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.initReader(DLOFDReader.java:88) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.(DLOFDReader.java:63) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:41) ~[ofdrw-converter-1.7.3.jar:na]
> > at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:107) ~[ofdrw-converter-1.7.3.jar:na]
> 
> **经过debug,发现解压的ofd文件目录为\Doc_0\Tpls\Tpl_0，但是读取到Document.xml->TemplatePage->BaseLoc 为TPLS/Tpl_0/Content.xml， Windows系统下文件路径大小写不敏感不会报错，但是Linux下会报错。**

该问题是因为文件路径和实际路径不匹配问题，应该是生成文档时候不规范造成的，不提供兼容，否则会出现 错误的引用问题。

**Comment by uu-xixi** [comment]
> 在**Linux**环境下，由于路径大小写敏感问题，导致读不到\Doc_0\Tpls\Tpl_0下内容。 [测试ofd文件](https://github.com/Trisia/ofdrw/blob/master/ofdrw-converter/src/test/resources/%E5%8F%91%E7%A5%A8%E7%A4%BA%E4%BE%8B.ofd) 重现如下（系统Ubuntu20.04）:
> 
> ```java
>     @PostMapping("/odfToPdf")
>     public void ofdToPdf(MultipartFile file, HttpServletResponse response) throws IOException {
>         try (InputStream input = file.getInputStream(); OutputStream output = response.getOutputStream()) {
>             response.setContentType(MediaType.APPLICATION_PDF_VALUE);
>             ConvertHelper.toPdf(input, output);
>         }
>     }
> ```
> 
> > 报错
> > org.ofdrw.reader.ErrorPathException: 无法切换路径到TPLS/Tpl_0/，目录不存在。
> > at org.ofdrw.reader.ResourceLocator.cd(ResourceLocator.java:233) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:376) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:352) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.getTemplateInfo(DLOFDReader.java:135) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.getOFDPageVO(DLOFDReader.java:157) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.initReader(DLOFDReader.java:88) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.reader.DLOFDReader.(DLOFDReader.java:63) ~[ofdrw-reader-1.7.3.jar:na]
> > at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:41) ~[ofdrw-converter-1.7.3.jar:na]
> > at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:107) ~[ofdrw-converter-1.7.3.jar:na]
> 
> **经过debug,发现解压的ofd文件目录为\Doc_0\Tpls\Tpl_0，但是读取到Document.xml->TemplatePage->BaseLoc 为TPLS/Tpl_0/Content.xml， Windows系统下文件路径大小写不敏感不会报错，但是Linux下会报错。**

您好，我也遇到了跟您类似的问题。暂时没有找到好的解决办法，请问一下 你那儿解决了吗？

**Comment by uu-xixi** [comment]
> 

您好作者，我也遇到了跟楼主一样的问题，在linux环境下面 由于路径大小写敏感问题，导致读不到\Doc_0\Tpls\Tpl_0内容。 请问有好的解决办法或者思路么

**Comment by agzou** [comment]
> > 在**Linux**环境下，由于路径大小写敏感问题，导致读不到\Doc_0\Tpls\Tpl_0下内容。 [测试ofd文件](https://github.com/Trisia/ofdrw/blob/master/ofdrw-converter/src/test/resources/%E5%8F%91%E7%A5%A8%E7%A4%BA%E4%BE%8B.ofd) 重现如下（系统Ubuntu20.04）:
> > ```java
> >     @PostMapping("/odfToPdf")
> >     public void ofdToPdf(MultipartFile file, HttpServletResponse response) throws IOException {
> >         try (InputStream input = file.getInputStream(); OutputStream output = response.getOutputStream()) {
> >             response.setContentType(MediaType.APPLICATION_PDF_VALUE);
> >             ConvertHelper.toPdf(input, output);
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 报错
> > > org.ofdrw.reader.ErrorPathException: 无法切换路径到TPLS/Tpl_0/，目录不存在。
> > > at org.ofdrw.reader.ResourceLocator.cd(ResourceLocator.java:233) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:376) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.reader.ResourceLocator.get(ResourceLocator.java:352) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.reader.DLOFDReader.getTemplateInfo(DLOFDReader.java:135) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.reader.DLOFDReader.getOFDPageVO(DLOFDReader.java:157) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.reader.DLOFDReader.initReader(DLOFDReader.java:88) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.reader.DLOFDReader.(DLOFDReader.java:63) ~[ofdrw-reader-1.7.3.jar:na]
> > > at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:41) ~[ofdrw-converter-1.7.3.jar:na]
> > > at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:107) ~[ofdrw-converter-1.7.3.jar:na]
> > 
> > 
> > **经过debug,发现解压的ofd文件目录为\Doc_0\Tpls\Tpl_0，但是读取到Document.xml->TemplatePage->BaseLoc 为TPLS/Tpl_0/Content.xml， Windows系统下文件路径大小写不敏感不会报错，但是Linux下会报错。**
> 
> 您好，我也遇到了跟您类似的问题。暂时没有找到好的解决办法，请问一下 你那儿解决了吗？

生成的odf文件有问题，只能修改源码，去适配

**Comment by uu-xixi** [comment]
> 
@agzou  请问一下 最后您哪儿解决了么？

**Comment by agzou** [comment]
> > 
> 
> @agzou 请问一下 最后您哪儿解决了么？

@uu-xixi 没呢，换了个ofd文件就可以了，不规范的不适配
