### ISSUE TITLE
关于页面边界处理

### ISSUE THREAD

**Issue by sssofall** [Trisia/ofdrw#11]
感谢作者的辛苦工作~
在使用布局过程中遇到一些问题
我的目标是使用绝对定位来指定 Div 或 Paragraph 的位置，并搭建一个电子版式
简单的测试代码如下：
```java
		Path path = Paths.get("test.ofd").toAbsolutePath();
		try (OFDDoc ofdDoc = new OFDDoc(path)) {
			VirtualPage virtualPage = new VirtualPage(210.0, 140.0);
			Paragraph p = new Paragraph("helloword");
			p.setPosition(Position.Absolute);
			p.setX(0.0);
			p.setY(0.0);
			p.setWidth(210.0 - 0.5);
			p.setHeight(140.0 - 0.5);
			p.setBorder(0.25);
			p.setPadding(0.0);
			p.setMargin(0.0);
			virtualPage.add(p);
			ofdDoc.addVPage(virtualPage);
		}
		System.out.println("out path: " + path.toAbsolutePath());
```
按照代码预期，应该是创建一个 Paragraph，其占满整个页面，并在页面最边缘描边
生成后的（数科）打开效果如下：
![image](https://github.com/sssofall/gallery/blob/master/20200401_001.png?raw=true)
可以看到有个层遮住了上、左位置的边框，VirtualPage 似乎没有办法指定 Padding、Margin
望回复，谢谢~

**Comment by Trisia** [comment]
根据Word的默认页面设置，页边距是 宽： 31.7毫米， 高:25.4，OFD R&W也采用这个默认设置。

如果你想使用某个页面的全部页面空间，你可以设置`VirtualPage`的`style`属性来设置相关属性，如下
```java
VirtualPage virtualPage = new VirtualPage(210.0, 140.0);
virtualPage.getStyle().setMargin(0d);
```

如果你需要设置整个文档的页面样式，那么你需要在创建文档的时候设置相关属性如下：
```java
try (OFDDoc ofdDoc = new OFDDoc(path)) {
    ofdDoc.setDefaultPageLayout(PageLayout.A4.setMargin(0d))
     // 你的布局代码
}
```

至于数科的这个现象我猜测可能是数科阅读器在显示上的问题，我尝试使用你的代码运行的得到的确实 顶边和左边边框看起来不见了

![image](https://user-images.githubusercontent.com/17817790/78097973-61f58300-7410-11ea-9618-191e9589be0b.png)

但是如果你把这个文档放大了之后再观察边框细节，你会发现这些边框右出现了。

![image](https://user-images.githubusercontent.com/17817790/78098037-8cdfd700-7410-11ea-9b65-36af20bf2a5e.png)

感谢你对OFD R&W的支持。

**Comment by sssofall** [comment]
感谢回复~ :-)
按照你提供的代码问题已解决，谢谢~
