### ISSUE TITLE
ofd转pdf输入参数问题

### ISSUE THREAD

**Issue by lugeluge** [Trisia/ofdrw#111]
![image](https://user-images.githubusercontent.com/16603407/111436654-306aea00-873d-11eb-85c4-66cd1438aad3.png)

建议将该参数改名，以免混淆，然后修改参数类型为double或者float

**Comment by Trisia** [comment]
该参数意义是 每毫米像素数量(Pixels per millimeter)，缩写也即`ppm` 对于以像素是整形单位，因此仅调整参数名称。
