### ISSUE TITLE
ofd转图像或者pfd遇到的问题

### ISSUE THREAD

**Issue by lugeluge** [Trisia/ofdrw#112]
请问ofd转图像和pdf，有考虑过多层ofd在转的时候的渲染顺序吗。

![9UU6DKBK10U3R)1ETF3K5_R](https://user-images.githubusercontent.com/16603407/111935160-d6cc3c00-8afd-11eb-9677-db10e3ea27d5.png)

左边的是文字隐藏在图像下方的双层ofd，右边是转出来的图像的效果，文字渲染在图像上方了,应该是渲染顺序问题，另外
可以把文字的fill属性作为判断是否需要渲染
![image](https://user-images.githubusercontent.com/16603407/111935319-2f033e00-8afe-11eb-9628-0e428f5f7e2e.png)

**Comment by Trisia** [comment]
你可以尝试一下然后提交pr

**Comment by lugeluge** [comment]
好的

**Comment by Trisia** [comment]
> 以把文字的fill属性作为判断是否需要渲染

我看了下如果根据`fill`属性，可能造成其他类型文档转换出来与预期不符。
