### ISSUE TITLE
jpg格式转ofd之后能否还原

### ISSUE THREAD

**Issue by joker-jrz** [Trisia/ofdrw#114]
目标：jpg转ofd文件后，再经过ofd转jpg能得到和之前一模一样（二进制文件一样或者说MD5值一样）的jpg文件
问题：jpg格式转ofd文件之后 ofd文件比jpg文件更小，生成ofd文件时是否经过压缩或者调整。或者怎么做才能达到预期目标
![image](https://user-images.githubusercontent.com/57607621/115493143-c098d380-a295-11eb-8b7c-0c84c8a3946b.png)

**Comment by joker-jrz** [comment]
已解决

**Comment by xialei2821212670** [comment]
> 已解决
怎么解决

**Comment by joker-jrz** [comment]
好像在c盘某个地方会生成一个 原始文件
