### ISSUE TITLE
ofd转PDF？

### ISSUE THREAD

**Issue by dockworkerjava** [Trisia/ofdrw#12]
您好，大神，感谢您提供ofd R&W，我在您的基础上实现了ofd解析以及ofd转PDF的功能，但是我是通过基础API实现的，我想通过您的高阶API实现 解析和转换的功能，您能给我提供点思路吗？

**Comment by dockworkerjava** [comment]
电子签章和水印也是在您的基础上完成了，但是都是基础API实现，代码量比较大， 操作比较繁琐，想通过您的高阶AP实现，希望您可以提供店思路

**Comment by Trisia** [comment]
> 您好，大神，感谢您提供ofd R&W，我在您的基础上实现了ofd解析以及ofd转PDF的功能，但是我是通过基础API实现的，我想通过您的高阶API实现 解析和转换的功能，您能给我提供点思路吗？

如果你实现了OFD -> PDF 的功能，欢迎提供合并Pull Request。

目前我对于你的问题存在一些疑惑，主要是“高阶API” 解析和转换的功能这个能够说详细些吗？

PDF的格式我也相对熟悉的，你的转化是通过建立对应类型的映射来把OFD图元转化为PDF的Obj这样吗？

如果是这样转化，有很多的重复操作如果能够封装倒是挺不错。 

如果可以我还是希望你能够提交一个Pull Request或者给我一个你项目的地址，我可以分析一下，我也能更加了解你们的使用情况，进而改进OFDRW。

谢谢

**Comment by Trisia** [comment]
> 电子签章和水印也是在您的基

另外电子签章和水印已经在我的日程当中，过几天就会出一个设计文档，然后增加新的API和模块

- **ofdrw-sign**
