### ISSUE TITLE
修改页面添加图片

### ISSUE THREAD

**Issue by heheidiot** [Trisia/ofdrw#17]
Path outPath = Paths.get("E:/testofd/dp.ofd");
 Path imgFile = Paths.get("E:/testofd/testpic","test.png");
 try (OFDReader reader = new OFDReader(srcTemp);
             OFDDoc oFDDoc = new OFDDoc(reader, outPath)){
AdditionVPage avPage = oFDDoc.getAVPage(1);
            Img a = new Img(10d,20d,imgFile);
            a.setPosition(Position.Absolute);
            a.setX(1.39D) .setY(7D).setMargin(3d)
                .setBorder(1d).setOpacity(1D);
            avPage.add(a);
}
您好，我想向页面中添加一张图片，为什么这样写并没有显示呢？只显示了图片区域的1d边框，但是图片内容没有，边框里面就是空白的

**Comment by Trisia** [comment]
我猜测你这个是由于页面预设的页边距造成的，你可以尝试设置页面页边距为0尝试下

#11

**Comment by heheidiot** [comment]
非常感谢您的帮助和回答，我找到问题原因了，原因是【DocumentRes.xml】里面我少写了个【BaseLoc="Res"】

**Comment by Trisia** [comment]
> 非常感谢您的帮助和回答，我找到问题原因了，原因是【DocumentRes.xml】里面我少写了个【BaseLoc="Res"】

如果问题得到解决请关闭问题。

**Comment by heheidiot** [comment]
好的好的
