### ISSUE TITLE
感谢大神的代码,我正以您的基础尝试嵌入电子印章

### ISSUE THREAD

**Issue by admin-kevin** [Trisia/ofdrw#2]
以您的代码尝试嵌入电子印章,目前已有进展,确实给我提供了很多思路,我也是个新手,以后多向大神学习.

**Comment by Trisia** [comment]
欢迎使用OFD R&W 目前ofd-pkg 模块还不太完善，在xml文件的序列化和反序列化过程中可能会有格式上的损失（如：空格、换行等）这些损失可能导致签名的验证和签名的完整性不一致，在完成OFD-layout之后我将会提出一个新的包 ofd-sign 专用于处理电子签章/电子签名的问题。

谢谢那你的使用老铁。

**Comment by nswish** [comment]
强烈支持!

**Comment by shaunlix** [comment]
吐血支持！！我在从头开始写，github竟然真的可以找到。

**Comment by sdhqw** [comment]
强烈支持!

**Comment by Trisia** [comment]
> 以您的代码尝试嵌入电子印章,目前已有进展,确实给我提供了很多思路,我也是个新手,以后多向大神学习.

OFD R&W  `1.2.0` 版本实现了OFD的电子签章：

请参阅
- [签名签章 验证 快速入门](https://github.com/Trisia/ofdrw/blob/master/ofdrw-sign/doc/quickstart/README.md)

**Comment by Trisia** [comment]
> 以您的代码尝试嵌入电子印章,目前已有进展,确实给我提供了很多思路,我也是个新手,以后多向大神学习.

如果该问题得到解决请关闭issue

**Comment by admin-kevin** [comment]
> > 以您的代码尝试嵌入电子印章,目前已有进展,确实给我提供了很多思路,我也是个新手,以后多向大神学习.
> 
> 如果该问题得到解决请关闭issue

大神,我这边自己集成了sm2证书生成,sm2签名算法,印模生成,印章生成及ofd签章的盖章及骑缝章,我想得到您ofd解析部分授权,我将会在git中标注原文引用,若是您不支持,我将不会上传签章部分代码,只供自己学习使用.
