### ISSUE TITLE
注释文件的文件名可否使用自定义文件名

### ISSUE THREAD

**Issue by leonsu7774** [Trisia/ofdrw#21]
Trisia：您好！
    默认的注释文件的文件名是“Annotation.xml”，我查了一下标准，标准上只对入口的文件名有规定：Annotations.xml，但是对每页的注释文件名没有做要求，但ofdrw对此做了限制，只能是Annotation.xml，不太方便，能否开放出来，增加一个方法，允许设置自定义的注释文件名，如果未写，则使用“Annotation.xml”。感谢。

**Comment by leonsu7774** [comment]
自行解决了

**Comment by Trisia** [comment]
> 自行解决了

你这里是什么原因需要这样的调整，如果是reader的话你可以自己拟定文件名。

因为没有标准约束所以我只能以Annotations.xml作为文件名，文件命名逻辑上也比较合理。
