### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by leonsu7774** [Trisia/ofdrw#22]
Annot类，只能调用一次addParameter，第2次再调用时，会报错：org.dom4j.IllegalAddException: The node "org.ofdrw.core.OFDElement@371a67ec" could not be added to the element "ofd:Annot" because: The Node already has an existing parent of "ofd:Annot"

测试代码如下：
public class AnnotTest {

    public static Annot annotCase() {
        Appearance appearance = new Appearance(new ST_Box(50, 50, 200, 200))
                .addPageBlock(PathObjectTest.pathObjectCase());

        return new Annot()
                .setID(new ST_ID(19))
                .setType(AnnotType.Path)
                .setCreator("ofdrw")
                .setLastModDate(LocalDate.now())
                .setRemark("这是一段说明内容")
                .addParameter("Key", "Value")
                .addParameter("qzh", "0001") //这里报错
                .setAppearance(appearance);
    }
    @Test
    public void gen() throws Exception {
        TestTool.genXml("Annot", annotCase());
    }
}

**Comment by leonsu7774** [comment]
解决方案：
修改Annot.java的addParameter方法，改成如下：
public Annot addParameter(String name, String parameter) {
        if (name == null || name.trim().length() == 0) {
            return this;
        }

        Element parameters = this.getOFDElement("Parameters");
        if (parameters == null) {
            parameters = OFDElement.getInstance("Parameters");
            this.add(parameters);//新增
        }
        OFDElement parameterEl = new OFDSimpleTypeElement("Parameter", parameter);
        parameterEl.addAttribute("Name", name);
        parameters.add(parameterEl);
        //this.add(parameters);
        return this;
    }

**Comment by leonsu7774** [comment]
这是修改完后的代码，因为不能push，所以贴这里了

public Annot addParameter(String name, String parameter) {
        if (name == null || name.trim().length() == 0) {
            return this;
        }

        Element parameters = this.getOFDElement("Parameters");
        if (parameters == null) {
            parameters = OFDElement.getInstance("Parameters");
            this.add(parameters);
        }
        Iterator<Element> iterator = parameters.elementIterator();
        Boolean foundKey = false;
        while (iterator.hasNext()) {
            Element element = iterator.next();
            if (element.attribute("Name").getValue().equalsIgnoreCase(name)) {
                element.setText(parameter);
                foundKey = true;
                break;
            }
        }
        if (!foundKey) {
            OFDElement parameterEl = new OFDSimpleTypeElement("Parameter", parameter);
            parameterEl.addAttribute("Name", name);
            parameters.add(parameterEl);
        }
        return this;
    }

**Comment by Trisia** [comment]
您可以先fork 项目，然后将修改提交到你自己仓库中的fork的该项目中，然后点击 pull request，我就可以合并您的分支。

**Comment by Trisia** [comment]
> 好的，我在gitee上pr了，这边也需要先fork再pr吗？


gitee 上的主要是从github上进行同步，所以修改以github为准。

**Comment by leonsu7774** [comment]
好的，我在github上创建pr了

**Comment by Trisia** [comment]
> 好的，我在github上创建pr了

已经PR完成，您的代码将在接下来的`v1.5.2`中出现

**Comment by Trisia** [comment]
> 好的，我在github上创建pr了

`  if (element.attribute("Name").getValue().equalsIgnoreCase(name)) `

我认为改为大小写敏感比较合适

`  if (element.attribute("Name").getValue().equals(name)) `

**Comment by leonsu7774** [comment]
嗯，好的
