### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by can0526** [Trisia/ofdrw#25]
将ofdrw打成jar包 打入到web项目当中
![image](https://user-images.githubusercontent.com/40846079/85351375-26151a00-b536-11ea-82ce-ea26c9892714.png)
解决方式
![image](https://user-images.githubusercontent.com/40846079/85351381-2b726480-b536-11ea-88fc-a0a3a7ff261e.png)
我的这种解决方式虽然没报错了，但是我理解上还不够，也不能确定这是一个bug，可能是我的理解不够，望作者指点一下。

**Comment by Trisia** [comment]
你可以直接使用已经发布到Maven中央仓库的版本，不需要自己打包

```
<dependency>
  <groupId>org.ofdrw</groupId>
  <artifactId>ofdrw-full</artifactId>
  <version>1.5.2</version>
</dependency>
```

**Comment by Trisia** [comment]
> 将ofdrw打成jar包 打入到web项目当中
> ![image](https://user-images.githubusercontent.com/40846079/85351375-26151a00-b536-11ea-82ce-ea26c9892714.png)
> 解决方式
> ![image](https://user-images.githubusercontent.com/40846079/85351381-2b726480-b536-11ea-88fc-a0a3a7ff261e.png)
> 我的这种解决方式虽然没报错了，但是我理解上还不够，也不能确定这是一个bug，可能是我的理解不够，望作者指点一下。

该问题已经修复了，提交到master分支了，下个版本一起发布。
