### ISSUE TITLE
请问一下 有没有删除签章的功能

### ISSUE THREAD

**Issue by can0526** [Trisia/ofdrw#26]

**Comment by Trisia** [comment]
目前没有，如果需求比较大，可以考虑。

如果还有相同需求的开发者可以在该issue下留言，达到一定需求我会考虑进行开发。

**Comment by can0526** [comment]
@Trisia  作者 您好，删除签章能否提供一个思路（多个的签章，删除非最后一个签章，该怎么处理 ）

**Comment by Trisia** [comment]
> @Trisia 作者 您好，删除签章能否提供一个思路（多个的签章，删除非最后一个签章，该怎么处理 ）

就把相关的签名值文件、印章文件、还有签名列表文件中的记录删除了就可以，这个你可以参考标准。
