### ISSUE TITLE
Img类构造器的parseImg方法中FileInputSteam 没有关闭导致图片被占用无法删除

### ISSUE THREAD

**Issue by wangsm123** [Trisia/ofdrw#28]

**Comment by Trisia** [comment]
> _No description provided._

[ref commit: a44356a43bd3b2672b9021d46d78ec08702fa4ea](https://github.com/Trisia/ofdrw/commit/a44356a43bd3b2672b9021d46d78ec08702fa4ea)

**Comment by Trisia** [comment]
建议使用 `Img(double width, double height, Path src) `构造器，使用`Img(Path src)` 图片大小为实际象素的1/5比例换算为OFD中的单位，多数情况下需要精密布局的场景，不太适合。
