### ISSUE TITLE
解析ofd兼容问题

### ISSUE THREAD

**Issue by DLTech21** [Trisia/ofdrw#31]
目前发现命名空间的常量写死了http://www.ofdspec.org/2016，这对按照新规范的ofd解析是没有问题的，但是如果用了旧标准的ofd，带的命名空间是http://www.ofdspec.org，那么目前的代码是没法解析ofd，望兼容

**Comment by Trisia** [comment]
不存在向下兼容，版本文档的标准目前只有一版，不符合标准的按照原则上来说是不应该承认为符合国标板式文档。

如果兼容意味着认可这类文档，对于没有任何依据的这类兼容，我倾向不兼容。

**Comment by DLTech21** [comment]
或者我提交个版本，你合并下，其实就是两个位置的改动？
