### ISSUE TITLE
读取【数科OFD软件V3.0 用户手册】时报错

### ISSUE THREAD

**Issue by zagpeng** [Trisia/ofdrw#34]
读取该文档时，zip4j报ZipException: Reached end of entry, but crc verification failed。使用java.util.zip包读取时没有这个异常

**Comment by Trisia** [comment]
请提供该文档 和发生错误的源码以及异常链路。

**Comment by leonsu7774** [comment]
和我遇到的问题一样，我已修改了解压方法，申请了一个PR。
产生问题的原因：数科OFD某些版本生成的ofd文件是非标zip，zip包的文件头不标准，已向数科提出了这个bug

**Comment by Trisia** [comment]
> 生问题的原因：数科OFD某些版本生成的ofd文件是非标zip，zip包的文件头不标

在 1.5.6 版本通过你的PR修复了该问题，非常感谢。

**Comment by tryob** [comment]
> 和我遇到的问题一样，我已修改了解压方法，申请了一个PR。
> 产生问题的原因：数科OFD某些版本生成的ofd文件是非标zip，zip包的文件头不标准，已向数科提出了这个bug

能否把你有问题的OFD上传一下/。？
