### ISSUE TITLE
Ofd文件解析内容顺序

### ISSUE THREAD

**Issue by DevinLeeQingZu** [Trisia/ofdrw#52]
请问下，ofd文件page页面解析出来的内容，目前看来似乎是page_x.xml中的textCode中的内容，顺序也是按照xml中的来的，但是这个顺序应该针对每张发票都不一样，这个解析出来的内容那应该也是动态可变的。是否可以固定顺序解析出来显示呢？
另外，当前功能是否可以支持将ofd文件转换为pdf或者图片样式呢？

**Comment by minghu-zhang** [comment]
> 请问下，ofd文件page页面解析出来的内容，目前看来似乎是page_x.xml中的textCode中的内容，顺序也是按照xml中的来的，但是这个顺序应该针对每张发票都不一样，这个解析出来的内容那应该也是动态可变的。是否可以固定顺序解析出来显示呢？
> 另外，当前功能是否可以支持将ofd文件转换为pdf或者图片样式呢？

这个解析是针对通用OFD文件的，不仅仅是发票，所以，解析顺序是动态的，如果你有固定顺序的需求，建议修改源码，提取需要的固定字段。目前不知道转pdf和转图片
