### ISSUE TITLE
如何修改一个现有的ofd文档？

### ISSUE THREAD

**Issue by zhangji261** [Trisia/ofdrw#6]
最近一直在关注这个项目，感谢作者的辛苦工作，想请教下如何修改一个现有的ofd文档？

**Comment by Trisia** [comment]
感谢你的支持！

修改ofd文档部分属于 OFD R&W 的 Reader 部分，该部分暂时还没有进行开发，但是这是OFD必须完成的功能，在之后的开发过程中会提供该功能。

目前来说如果你对OFD熟悉，你可以直接使用fdf-core提供的API操作对应的文档元素达到修改的效果，然后在通过 ofd-pkg 打包，流程相对复杂需要你对OFD有比较高的掌握才行。

**Comment by Trisia** [comment]
另外您可以提供一下你修改OFD文档的需求吗？需要修改什么内容？文字内容、图片、格式等。

**Comment by xPeanut** [comment]
编辑大多数的使用场景应该类似为：打开一个设计好的ofd（例如已经设计好的模板），向设计好的模板中指定区域填充文字或者图片。

**Comment by Trisia** [comment]
嗯嗯，确实有这种情况，那么主要也就是说是向页面中增加内容吧？

其实增加内容实现上来说是相对容易的，关键是修改原有的内容。

**Comment by 174639357** [comment]
你好，修改ofd文档的话，应该就是将文档中的xml反序列化成ofd-core中相应的对象，然后对对象进行操作，再用ofd-pkg对xml进行打包吧。我想问下有一个反序列化的例子嘛。。

**Comment by Trisia** [comment]
目前暂时没有写反序序列化的例子，如果只是对xml进行反序列化倒是容易，我认为还需要考虑反序列化OFD虚拟容器，建立对象的ID映射这样的反序列化可能比较好，反序列已经在日程中了，还在设计中。

**Comment by Trisia** [comment]
> 编辑大多数的使用场景应该类似为：打开一个设计好的ofd（例如已经设计好的模板），向设计好的模板中指定区域填充文字或者图片。

在ofdrw version: *1.1.0* 中提供页面内容追加的功能，示例代码如下：

```java
public static main() throws IOException {
    Path srcP = Paths.get("src/test/resources", "helloworld.ofd");
    Path outP = Paths.get("target/EditedDoc.ofd");
    try (OFDReader reader = new OFDReader(srcP);
         OFDDoc ofdDoc = new OFDDoc(reader, outP)) {
        AdditionVPage avPage = ofdDoc.getAVPage(1);
        Div e = new Div(10d, 10d)
                .setPosition(Position.Absolute)
                .setX(70d).setY(113.5)
                .setBackgroundColor(255, 192, 203)
                .setBorder(0.353d)
                .setPadding(5d);
        avPage.add(e);
    }
    System.out.println("生成文档位置：" + outP.toAbsolutePath().toString());
}
```

步骤如下：

1. 新建一个`OFDReader`，然后构造出`OFDDoc`。
2. 通过`OFDDoc`获取指定页面的`AdditionVPage`对象。
3. 同虚拟页面一致的方式，向页面中增加需要的内容。
4. 关闭文档和Reader。

> [测试用例](https://github.com/Trisia/ofdrw/blob/master/ofdrw-layout/src/test/java/org/ofdrw/layout/OFDDocTest.java) `#editTest()`，如果你需要追加页面请参考`#appendTest()`

**Comment by Trisia** [comment]
> 你好，修改ofd文档的话，应该就是将文档中的xml反序列化成ofd-core中相应的对象，然后对对象进行操作，再用ofd-pkg对xml进行打包吧。我想问下有一个反序列化的例子嘛。。

在ofdrw version *1.1.0* 重构了pkg，提供OFD虚拟容器。

如果需要实现对底层的OFD对象的操作（反序列化后修改等），那么你需要使用到OFD虚拟容器。

此处以修改文档作者为例，示例代码如下：
```java
public static main() throws IOException, DocumentException {
        Path out = Paths.get("target/EditTitleAuthor.ofd");
        try (OFDReader reader = new OFDReader(src)) {
            OFDDir ofdDir = reader.getOFDDir();
            OFD ofd = ofdDir.getOfd();
            DocBody docBody = ofd.getDocBody();
            CT_DocInfo docInfo = docBody.getDocInfo();
            System.out.println(">> 文档标题：[" + docInfo.getTile() +"] -> [Hello World]");
            System.out.println(">> 文档作者：[" + docInfo.getAuthor()+"] -> [权观宇]" );
            docInfo.setTile("Hello World");
            docInfo.setAuthor("权观宇");
            docInfo.setModDate(LocalDate.now());
            // 重新打包为OFD文档
            ofdDir.jar(out);
        }
        System.out.println(">> 文档生成位置："+ out.toAbsolutePath().toString());
}
```

> [测试用例](https://github.com/Trisia/ofdrw/blob/master/ofdrw-reader/src/test/java/org/ofdrw/reader/OFDReaderTest.java) `#lowLevelOp()`

步骤如下：

1. 使用现有文档构造一个`OFDReader`对象。
2. 从Reader对象中获取到虚拟容器`OFDDir`。
3. 使用虚拟容器提供的API获取需要修改的对象（反序列化对应的文件为OFD对象）。
4. 做你想做的事情。
5. 使用虚拟容器`OFDDir`提供的打包（`jar`）功能，将你修改的内容重新打包为OFD文档。

**Comment by Trisia** [comment]
> 最近一直在关注这个项目，感谢作者的辛苦工作，想请教下如何修改一个现有的ofd文档？

如果该问题得到解决，请关闭issue。

**Comment by zhangji261** [comment]
谢谢大神
