### ISSUE TITLE
电子签名是怎么实现的？

### ISSUE THREAD

**Issue by zhangji261** [Trisia/ofdrw#7]
电子签名和电子签章是怎么实现的？能否请大神提供点示例代码

**Comment by Trisia** [comment]
目前电子签章和数字签章 ofd r&w 暂时没有提供该功能，不过在之后的开发过程中应该会陆续补上。

具体新的功能何时上线，得看ofd-layout完成程度，但是签名签章功能也是OFD R&W的重要组成部分。

假如你对OFD结构十分熟悉，你可以根据标准实现该部分功能。

如果您对该项目有兴趣的话，请持续关注项目进展。

**Comment by Trisia** [comment]
> 电子签名和电子签章是怎么实现的？能否请大神提供点示例代码

如果该问题得到解决，请关闭issue
