### ISSUE TITLE
文件流操作

### ISSUE THREAD

**Issue by chouxiaozi** [Trisia/ofdrw#86]
所有的功能代码都是从文件读取数据的，能不能添加从流读取数据的方法

**Comment by Trisia** [comment]
鼓励使用 java nio

**Comment by minghu-zhang** [comment]
流读取数据的话，也需要写到文件的，因为是个压缩包，流没读取完的话，解压不出来

**Comment by minghu-zhang** [comment]
> 所有的功能代码都是从文件读取数据的，能不能添加从流读取数据的方法
正在开发。

**Comment by Trisia** [comment]
预计在 1.7.0 版本对流全面支持

感谢 @minghu-zhang  的贡献

**Comment by chouxiaozi** [comment]
将来有功能项可以排给我点，现在有点忙所以伸手党了，多谢多谢
