### ISSUE TITLE
支持pdf或图片转换吗

### ISSUE THREAD

**Issue by hglei** [Trisia/ofdrw#9]
请问您有计划增加ofd格式到pdf格式或者图片的转换功能吗

**Comment by Trisia** [comment]
目前暂时不支持哦

OFD R&W 在前面的阶段只是对OFD文档的生成，以及操作为主。

格式转换和这个涉及到图像图像的绘制和渲染，以及不同文档格式理解，在未来可能会支持，不过现阶段，暂时没有很好的解决方案。
