### ISSUE TITLE
在close的时候内存溢出

### ISSUE THREAD

**Issue by wangsm123** [Trisia/ofdrw#94]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.zip.ZipCoder.getBytes(ZipCoder.java:80)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:316)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1042)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.ofdrw.pkg.container.VirtualContainer.clean(VirtualContainer.java:346)
	at org.ofdrw.layout.OFDDoc.close(OFDDoc.java:468)

**Comment by wangsm123** [comment]
我在ofd中加了很多Paragraph，然后在打包OFD时报错，内存溢出

**Comment by Trisia** [comment]
请给出报错示例代码，和使用库版本。

**Comment by minghu-zhang** [comment]
> 我在ofd中加了很多Paragraph，然后在打包OFD时报错，内存溢出

能把示例代码上传到git么

**Comment by wangsm123** [comment]
稍后我来贴一下代码







---原始邮件---
发件人: "minghu.zhang"<notifications@github.com&gt;
发送时间: 2020年11月20日(周五) 晚上6:49
收件人: "Trisia/ofdrw"<ofdrw@noreply.github.com&gt;;
抄送: "wangsm123"<807125562@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Trisia/ofdrw] 在close的时候内存溢出 (#94)




  
我在ofd中加了很多Paragraph，然后在打包OFD时报错，内存溢出
  
能把示例代码上传到git么

**Comment by minghu-zhang** [comment]
> 稍后我来贴一下代码
> […](#)
> ---原始邮件--- 发件人: "minghu.zhang"<notifications@github.com&gt; 发送时间: 2020年11月20日(周五) 晚上6:49 收件人: "Trisia/ofdrw"<ofdrw@noreply.github.com&gt;; 抄送: "wangsm123"<807125562@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [Trisia/ofdrw] 在close的时候内存溢出 (#94) 我在ofd中加了很多Paragraph，然后在打包OFD时报错，内存溢出 能把示例代码上传到git么 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

使用这种方式提交
![image](https://user-images.githubusercontent.com/28996118/99794452-25c08f80-2b65-11eb-9803-1e6a7f05307b.png)

**Comment by wangsm123** [comment]
for(int i=0; i<jsonArray.size();i++){
            JSONObject object=jsonArray.getJSONObject(i);
            JSONArray characters=object.getJSONArray("characters");
            for(int j=0;j<characters.size();j++){
                JSONObject childP=characters.getJSONObject(j);
                JSONObject location=childP.getJSONObject("location");
                String word=childP.getString("code");
                double left=location.getDoubleValue("left");
                left*=k;
                double right=location.getDoubleValue("right");
                right*=k;
                double top=location.getDoubleValue("top");
                top*=k;
                double bottom=location.getDoubleValue("bottom");
                bottom*=k;
                Span span=new Span(word);
                double width=new BigDecimal(right-left).setScale(2, RoundingMode.UP).doubleValue();
                double height=new BigDecimal(bottom-top).setScale(2, RoundingMode.UP).doubleValue();
                span.setFontSize(height);
                System.out.println(word);
                System.out.println("width"+width+"height:"+height);
                Paragraph p = new Paragraph(width*2,height*2);
                p.add(span);
                p.setPosition(Position.Absolute).setY(top).setX(left);
                vPage.add(p);
            }
ofdDoc.addVPage(vPage);
        ofdDoc.close();

**Comment by wangsm123** [comment]
我的这种写法是有问题吗

**Comment by Trisia** [comment]
应该是没有问题的呀

**Comment by wangsm123** [comment]
我的循环里加的段比较多，可能上千个



---原始邮件---
发件人: "Quan guanyu"<notifications@github.com&gt;
发送时间: 2020年11月25日(周三) 上午9:01
收件人: "Trisia/ofdrw"<ofdrw@noreply.github.com&gt;;
抄送: "wangsm123"<807125562@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Trisia/ofdrw] 在close的时候内存溢出 (#94)




 
应该是没有问题的呀

**Comment by Trisia** [comment]
你把JVM的内存参数调大些试试
