### ISSUE TITLE
flush文件的时候不能传入dom4j提供的xml的format

### ISSUE THREAD

**Issue by SinjinLee** [Trisia/ofdrw#95]
try (OutputStream out = Files.newOutputStream(to)) {
            XMLWriter writeToFile = new XMLWriter(out);
            writeToFile.write(doc);
            writeToFile.close();
        }

能否提供XMLWriter(OutputStream out, OutputFormat format);
org.ofdrw.pkg.container.OFDDir#jar

**Comment by Trisia** [comment]
我不认为，格式化的文档对于阅读器或者解析器有什么帮助，而且会消耗多余的空间。

**Comment by minghu-zhang** [comment]
不建议这样做，会消耗额外的资源，而且没有意义

**Comment by minghu-zhang** [comment]
不建议这样做，会消耗额外的资源，而且没有意义
